### ISSUE TITLE
Discussion: Jekyll theme

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/docs.simplyrets.com#5]
I started with [minima](https://github.com/jekyll/minima) because it has a lot of options for nav/footer links, and obviously blog posts.

Here's what it looks like right now (I disabled GH pages -- if you test it be sure to disable it afterwards until we are ready to move over so it doesn't get indexed by Google):

![image](https://user-images.githubusercontent.com/7034627/47481908-abdd4100-d7fa-11e8-8657-e8fd9908f5a0.png)

I'll run with this a little longer unless there are any objections.

**Comment by creichert** [comment]
See my comments on #4. I think just start simple and add everything to a
single big index page then expand. This theme is the best one for now
because all we need are "accent" colors.

Keep the white base and add a dead simple nav (if it's even needed).

I'll get updates and alerts. Unassigning until actionable.

**Comment by creichert** [comment]
Yeah, the doc you posted looks good for a start. Consider how to add more "space" as it's very dense. Likely a TOC will do well and should relate to our primary "products" (Wordpress, API, Geocoding).
